[package]
name = "Load_a_local_json_file_keypair"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "2.3.1"
solana-client = "2.3.6"
tokio = "1.47.1"
anyhow = "1.0.98"
futures = "0.3.31"
serde_json = "1.0.142"
